---
title: "exercise_3"
author: "Cyril Geistlich"
date: "2023-05-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library("readr") 
library("sf") 
library("ggplot2") # to visualize data
library("gitcreds")
library("dplyr")
```

```{r prep data}
boar<- read_delim("data/wildschwein_BE_2056.csv", ",")
boar$TierName |> unique()



sabi <- boar |> 
  filter(TierName == 'Sabi') |>
  filter(DatetimeUTC >= as.POSIXct("2015-07-01", tz = "UTC"), DatetimeUTC < as.POSIXct("2015-07-03", tz = "UTC"))
```

```{r visualize 1}
ggplot(sabi,aes(E,N, color = DatetimeUTC)) +
  geom_point() +
  geom_path() + 
  coord_equal()
```
```{r sampling interval}

sabi |>
  head(50) |>
  ggplot(aes(DatetimeUTC, 1)) +
  geom_point() +
  ggtitle("Sampling Interval Sabi")

```
```{r eucl distance}
sabi |> 
  mutate(
    stepLength = sqrt((lead(E)-E)**2 + (lead(N)-N)**2)
    )
```   
```{r}
sabi <- sabi |>
    mutate(
        nMinus2 = sqrt((lag(E, 2) - E)^2 + (lag(N, 2) - N)^2), 
        # distance to pos -30 minutes
        nMinus1 = sqrt((lag(E, 1) - E)^2 + (lag(N, 1) - N)^2), 
        # distance to pos -15 minutes
        nPlus1  = sqrt((E - lead(E, 1))^2 + (N - lead(N, 1))^2), 
        # distance to pos +15 mintues
        nPlus2  = sqrt((E - lead(E, 2))^2 + (N - lead(N, 2))^2) 
        # distance to pos +30 minutes
    )
```

```{r}
sabi <- sabi |>
    rowwise() |>
    mutate(
        stepMean = mean(c(nMinus2, nMinus1, nPlus1, nPlus2))
    ) |>
    ungroup()

sabi
```

```{r remove static points}
sabi <- sabi |>
    ungroup() |>
    mutate(static = stepMean < mean(stepMean, na.rm = TRUE))

sabi_filter <- sabi |>
    filter(!static)

sabi_filter |>
    ggplot(aes(E, N, color = DatetimeUTC)) +
    geom_path() +
    geom_point() +
    coord_fixed()
```
```{r}
ggplot(sabi, aes(stepMean)) +
  geom_histogram(binwidth = 10)
```
```{r vis static points}
sabi |>
  mutate(
    static = stepMean < mean(stepMean, na.rm = TRUE)
  ) |> 
  ggplot(aes(E,N)) +
  geom_point(aes(color = static)) +
  geom_path() +
  coord_fixed()
```

```{r read posmo}
posmo <- read_delim("data/posmo_2023-04-28T00_00_00+02_00-2023-04-30T23_59_59+02_00.csv", ",")
posmo <-  select(posmo, datetime, lon_x, lat_y)
posmo <- st_as_sf(posmo,coords = c("lon_x","lat_y"), crs = 4326) 
posmo <- st_transform(posmo, crs = 2056)
```

```{r prep data}
posmo_coordinates <- st_coordinates(posmo)
posmo <- cbind(posmo, posmo_coordinates)
posmo <- posmo |>
    filter(as.Date(datetime) == "2023-04-29")
```

# Task 1: Segmentation

```{r sampling interval Posmo}
posmo |>
  ggplot(aes(datetime, 1)) +
  geom_point() +
  ggtitle("Sampling Interval Posmo")

```

# Task 2: Specify and apply threshold distance

```{r steplenght Posmo}
posmo |> 
  mutate(
    stepLength = sqrt((lead(X)-X)**2 + (lead(Y)-Y)**2)
    )
```
```{r prep stepmean}
posmo <- posmo |>
    mutate(
        nMinus2 = sqrt((lag(X, 2) - X)^2 + (lag(Y, 2) - Y)^2), 
        nMinus1 = sqrt((lag(X, 1) - X)^2 + (lag(Y, 1) - Y)^2), 
        nPlus1  = sqrt((X - lead(X, 1))^2 + (Y - lead(Y, 1))^2), 
        nPlus2  = sqrt((X - lead(X, 2))^2 + (Y - lead(Y, 2))^2) 
    )
```

```{r calc stepmean}
posmo <- posmo |>
    rowwise() |>
    mutate(
        stepMean = mean(c(nMinus2, nMinus1, nPlus1, nPlus2))
    ) |>
    ungroup()


posmo <- tidyr::drop_na(posmo)

posmo <- posmo |>
  ungroup() |>
  mutate(static = stepMean < mean(stepMean, na.rm = TRUE))

posmo_mean <- posmo |>
  filter(!static) 

```

```{r visualise stepmean}
ggplot(posmo, aes(stepMean)) +
  geom_histogram(binwidth = 10)
  
```

# Task 3: Visualise segmented trajectories

```{r visualise static}
posmo |>
    ggplot(aes(X, Y, color = static)) +
    geom_path() +
    geom_point() +
    coord_fixed() +
    ggtitle("False Flag stepMean < mean(stepmean)")

posmo_mean|>
    ggplot(aes(X, Y, color = datetime)) +
    geom_path() +
    geom_point() +
    coord_fixed()

  table(posmo$static)
```
# Task 4: Segment-based analysis

```{r assign id}


rle_id <- function(vec) {
    x <- rle(vec)$lengths
    as.factor(rep(seq_along(x), times = x))
}

rle_id(posmo$static)
```

```{r rename and filter static}

posmo <- posmo |>
    mutate(segment_id = rle_id(static)) |>
    filter(!static)



# assuming your dataframe is called 'df'
# and the column names are 'diff_s' and 'segment_id'

# create a new column 'diff_s_without_last' that has the same values as 'diff_s',
# except for the last value for each segment
df$diff_s_without_last <- ave(df$diff_s, df$segment_id, FUN = function(x) c(x[-length(x)], NA))

# sum the 'diff_s_without_last' column for each segment_id
sum_diff_s <- aggregate(df$diff_s_without_last, by=list(segment=df$segment_id), FUN=sum, na.rm=TRUE)

# rename the columns to something more descriptive
colnames(sum_diff_s) <- c("Segment ID", "Total Time (s)")

# print the resulting dataframe
print(sum_diff_s)




```
```{r}
posmo |>
    ggplot(aes(X, Y, color = segment_id)) +
    geom_path() +
    geom_point() +
    coord_fixed() + 
    ggtitle("Segmentation (All)")

posmo |> ggplot(aes(X, Y, color = segment_id)) +
    geom_path() +
    geom_point() +
    coord_fixed() + 
    ggtitle("Segmentation (> 5 minutes)")
```

  